import { 
  TeamMember, 
  Feature, 
  Testimonial, 
  KPICard, 
  ChartData, 
  CompanyMilestone, 
  CompanyValue,
  ContactInfo,
  SocialLinks,
  FinancialKPI,
  CashFlowData,
  BusinessMetrics,
  FinancialHealthIndicator,
  RevenueBreakdown,
  ExpenseCategory,
  ProfitMarginData,
  BankAccount,
  Transaction,
  PaymentMethod,
  QRPayment,
  OpenFinanceConnection,
  ConsolidatedFinancialData,
  TransactionCategory,
  SupplierCustomerData,
  ComplianceReport,
  TaxCalculation,
  Invoice,
  InvoiceItem,
  LanguageSupport
} from './types'
import { 
  Users, 
  TrendingUp, 
  Shield, 
  Zap, 
  Target, 
  Award, 
  Heart, 
  Globe,
  DollarSign,
  ShoppingCart,
  UserCheck,
  BarChart3,
  Building2,
  CreditCard,
  QrCode,
  ArrowUpDown,
  PieChart,
  FileText,
  Calculator,
  Receipt,
  Truck,
  Store,
  Coffee,
  Car,
  Home,
  Smartphone,
  Utensils,
  Briefcase,
  Fuel,
  Stethoscope,
  GraduationCap,
  Gamepad2,
  Plane,
  Gift,
  Shirt,
  Wrench,
  Zap as ElectricIcon,
  Wifi,
  Music,
  Film,
  Book,
  Dumbbell,
  Scissors,
  Paintbrush,
  Flower,
  ShieldCheck,
  AlertCircle,
  CheckCircle2,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe2,
  Languages,
  Calendar,
  FileCheck,
  TrendingDown,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Minus,
  Plus,
  Eye,
  EyeOff,
  Loader,
  RefreshCw,
  Download,
  Upload,
  Filter,
  Search,
  Settings,
  Bell,
  HelpCircle,
  LogOut,
  User,
  Edit,
  Trash,
  Copy,
  Share,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  MoreHorizontal,
  MoreVertical
} from 'lucide-react'

// Company Information
export const companyInfo = {
  name: 'BizKuku',
  tagline: 'Empowering Business Growth Through Innovation',
  mission: 'To provide cutting-edge solutions that help businesses thrive in the digital age.',
  vision: 'To be the leading platform for business transformation and growth.',
  founded: '2020',
  employees: '150+',
  customers: '10,000+',
}

// Contact Information
export const contactInfo: ContactInfo = {
  email: 'hello@bizzku.com',
  phone: '+1 (555) 123-4567',
  address: '123 Innovation Drive, Tech City, TC 12345',
}

// Social Links
export const socialLinks: SocialLinks = {
  twitter: 'https://twitter.com/bizzku',
  linkedin: 'https://linkedin.com/company/bizzku',
  facebook: 'https://facebook.com/bizzku',
  instagram: 'https://instagram.com/bizzku',
  github: 'https://github.com/bizzku',
}

// Features Data
export const features: Feature[] = [
  {
    id: '1',
    title: 'Tengok Jualan • See Sales',
    description: 'Tengok berapa duit masuk hari ini dan bulan ini dengan mudah • See how much money came in today and this month easily.',
    icon: BarChart3,
  },
  {
    id: '2',
    title: 'Pantau Masa Nyata • Live Updates',
    description: 'Tengok jualan terkini setiap masa untuk buat keputusan bijak • See latest sales anytime to make smart decisions.',
    icon: TrendingUp,
  },
  {
    id: '3',
    title: 'Selamat & Boleh Harap • Safe & Reliable',
    description: 'Data anda selamat dan sistem sentiasa berfungsi untuk ketenangan fikiran • Your data is safe and system always works for peace of mind.',
    icon: Shield,
  },
  {
    id: '4',
    title: 'Pantas & Mudah • Fast & Easy',
    description: 'Sistem yang pantas dan mudah digunakan untuk semua orang • Fast and easy system for everyone to use.',
    icon: Zap,
  },
]

// Team Members Data
export const teamMembers: TeamMember[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    role: 'CEO & Founder',
    bio: 'Visionary leader with 15+ years in tech industry, passionate about innovation.',
    image: '/team/sarah.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/sarahjohnson',
      twitter: 'https://twitter.com/sarahjohnson',
    },
  },
  {
    id: '2',
    name: 'Michael Chen',
    role: 'CTO',
    bio: 'Technical expert specializing in scalable architecture and AI solutions.',
    image: '/team/michael.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/michaelchen',
      github: 'https://github.com/michaelchen',
    },
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    role: 'Head of Design',
    bio: 'Creative designer focused on user experience and beautiful interfaces.',
    image: '/team/emily.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/emilyrodriguez',
      twitter: 'https://twitter.com/emilyrodriguez',
    },
  },
  {
    id: '4',
    name: 'David Kim',
    role: 'Head of Marketing',
    bio: 'Growth expert with proven track record in scaling tech companies.',
    image: '/team/david.jpg',
    social: {
      linkedin: 'https://linkedin.com/in/davidkim',
      twitter: 'https://twitter.com/davidkim',
    },
  },
]

// Testimonials Data
export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Alex Thompson',
    role: 'CEO',
    company: 'TechStart Inc.',
    content: 'BizzKu transformed our business operations. The analytics insights helped us increase revenue by 40%.',
    avatar: '/testimonials/alex.jpg',
    rating: 5,
  },
  {
    id: '2',
    name: 'Maria Garcia',
    role: 'Operations Manager',
    company: 'Growth Co.',
    content: 'The real-time monitoring features are incredible. We can now respond to issues before they impact customers.',
    avatar: '/testimonials/maria.jpg',
    rating: 5,
  },
  {
    id: '3',
    name: 'James Wilson',
    role: 'Founder',
    company: 'InnovateLab',
    content: 'Outstanding platform with excellent customer support. Highly recommend for any growing business.',
    avatar: '/testimonials/james.jpg',
    rating: 5,
  },
]

// Company Values
export const companyValues: CompanyValue[] = [
  {
    id: '1',
    title: 'Innovation',
    description: 'We constantly push boundaries to deliver cutting-edge solutions.',
    icon: Target,
  },
  {
    id: '2',
    title: 'Excellence',
    description: 'We strive for perfection in everything we do.',
    icon: Award,
  },
  {
    id: '3',
    title: 'Integrity',
    description: 'We build trust through transparency and honest communication.',
    icon: Heart,
  },
  {
    id: '4',
    title: 'Global Impact',
    description: 'We aim to make a positive difference worldwide.',
    icon: Globe,
  },
]

// Company Milestones
export const companyMilestones: CompanyMilestone[] = [
  {
    id: '1',
    year: '2020',
    title: 'Company Founded',
    description: 'BizzKu was founded with a vision to revolutionize business analytics.',
  },
  {
    id: '2',
    year: '2021',
    title: 'First 1,000 Customers',
    description: 'Reached our first major milestone with 1,000 satisfied customers.',
  },
  {
    id: '3',
    year: '2022',
    title: 'Series A Funding',
    description: 'Secured $10M in Series A funding to accelerate growth.',
  },
  {
    id: '4',
    year: '2023',
    title: 'Global Expansion',
    description: 'Expanded operations to serve customers in 50+ countries.',
  },
  {
    id: '5',
    year: '2024',
    title: 'AI Integration',
    description: 'Launched AI-powered analytics features for predictive insights.',
  },
]

// KPI Cards Data
export const kpiData: KPICard[] = [
  {
    id: '1',
    title: 'Total Revenue',
    value: '$2.4M',
    change: 12.5,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Monthly recurring revenue',
  },
  {
    id: '2',
    title: 'Active Users',
    value: '45,231',
    change: 8.2,
    changeType: 'increase',
    icon: Users,
    description: 'Monthly active users',
  },
  {
    id: '3',
    title: 'Conversion Rate',
    value: '3.24%',
    change: -2.1,
    changeType: 'decrease',
    icon: UserCheck,
    description: 'Visitor to customer conversion',
  },
  {
    id: '4',
    title: 'Total Orders',
    value: '12,847',
    change: 15.3,
    changeType: 'increase',
    icon: ShoppingCart,
    description: 'Orders this month',
  },
]

// Chart Data
export const revenueData: ChartData[] = [
  { name: 'Jan', value: 1800000 },
  { name: 'Feb', value: 1950000 },
  { name: 'Mar', value: 2100000 },
  { name: 'Apr', value: 2250000 },
  { name: 'May', value: 2180000 },
  { name: 'Jun', value: 2400000 },
]

export const userGrowthData: ChartData[] = [
  { name: 'Jan', value: 32000 },
  { name: 'Feb', value: 35500 },
  { name: 'Mar', value: 38200 },
  { name: 'Apr', value: 41800 },
  { name: 'May', value: 43200 },
  { name: 'Jun', value: 45231 },
]

export const categoryData: ChartData[] = [
  { name: 'Desktop', value: 65 },
  { name: 'Mobile', value: 28 },
  { name: 'Tablet', value: 7 },
]

// Financial Analytics Mock Data
export const financialKPIs: FinancialKPI[] = [
  {
    id: 'monthly_revenue',
    title: 'Monthly Revenue',
    value: '$127,500',
    change: 18.5,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Total revenue this month',
    period: 'monthly',
    currency: 'USD',
    trend: 'up',
    target: 150000,
  },
  {
    id: 'gross_profit',
    title: 'Gross Profit',
    value: '$89,250',
    change: 22.3,
    changeType: 'increase',
    icon: TrendingUp,
    description: 'Profit after direct costs',
    period: 'monthly',
    currency: 'USD',
    trend: 'up',
    target: 105000,
  },
  {
    id: 'cash_flow',
    title: 'Net Cash Flow',
    value: '$34,720',
    change: -5.2,
    changeType: 'decrease',
    icon: BarChart3,
    description: 'Net cash flow this month',
    period: 'monthly',
    currency: 'USD',
    trend: 'down',
    target: 45000,
  },
  {
    id: 'profit_margin',
    title: 'Profit Margin',
    value: '27.8%',
    change: 3.1,
    changeType: 'increase',
    icon: Target,
    description: 'Gross profit margin',
    period: 'monthly',
    trend: 'up',
    target: 30,
  },
  {
    id: 'businesses_onboarded',
    title: 'Businesses Onboarded',
    value: '1,847',
    change: 31.2,
    changeType: 'increase',
    icon: Users,
    description: 'New businesses this month',
    period: 'monthly',
    trend: 'up',
    target: 2000,
  },
  {
    id: 'avg_transaction_value',
    title: 'Avg Transaction Value',
    value: '$68.50',
    change: -2.8,
    changeType: 'decrease',
    icon: ShoppingCart,
    description: 'Average transaction amount',
    period: 'monthly',
    currency: 'USD',
    trend: 'down',
    target: 75,
  },
]

export const cashFlowData: CashFlowData[] = [
  {
    name: 'Jan',
    date: '2024-01-01',
    income: 142000,
    expenses: 89000,
    netCashFlow: 53000,
    cumulativeCashFlow: 53000,
  },
  {
    name: 'Feb',
    date: '2024-02-01',
    income: 158000,
    expenses: 94000,
    netCashFlow: 64000,
    cumulativeCashFlow: 117000,
  },
  {
    name: 'Mar',
    date: '2024-03-01',
    income: 135000,
    expenses: 91000,
    netCashFlow: 44000,
    cumulativeCashFlow: 161000,
  },
  {
    name: 'Apr',
    date: '2024-04-01',
    income: 167000,
    expenses: 98000,
    netCashFlow: 69000,
    cumulativeCashFlow: 230000,
  },
  {
    name: 'May',
    date: '2024-05-01',
    income: 149000,
    expenses: 102000,
    netCashFlow: 47000,
    cumulativeCashFlow: 277000,
  },
  {
    name: 'Jun',
    date: '2024-06-01',
    income: 175000,
    expenses: 108000,
    netCashFlow: 67000,
    cumulativeCashFlow: 344000,
  },
]

export const businessMetrics: BusinessMetrics[] = [
  {
    id: 'onboarding_step_1',
    name: 'Basic Information',
    completionRate: 94.2,
    averageTime: 3.5,
    dropOffRate: 5.8,
    satisfactionScore: 4.3,
    date: '2024-06-01',
  },
  {
    id: 'onboarding_step_2',
    name: 'Business Documents',
    completionRate: 78.6,
    averageTime: 12.3,
    dropOffRate: 21.4,
    satisfactionScore: 3.8,
    date: '2024-06-01',
  },
  {
    id: 'onboarding_step_3',
    name: 'Bank Account Setup',
    completionRate: 85.1,
    averageTime: 8.7,
    dropOffRate: 14.9,
    satisfactionScore: 4.1,
    date: '2024-06-01',
  },
  {
    id: 'onboarding_step_4',
    name: 'Payment Gateway',
    completionRate: 72.4,
    averageTime: 15.2,
    dropOffRate: 27.6,
    satisfactionScore: 3.6,
    date: '2024-06-01',
  },
  {
    id: 'onboarding_step_5',
    name: 'Final Verification',
    completionRate: 91.8,
    averageTime: 6.1,
    dropOffRate: 8.2,
    satisfactionScore: 4.5,
    date: '2024-06-01',
  },
]

export const financialHealthIndicators: FinancialHealthIndicator[] = [
  {
    id: 'liquidity_ratio',
    name: 'Liquidity Ratio',
    value: 2.8,
    status: 'healthy',
    recommendation: 'Maintain current cash reserves',
    trend: 'stable',
  },
  {
    id: 'debt_to_equity',
    name: 'Debt-to-Equity',
    value: 0.4,
    status: 'healthy',
    recommendation: 'Good balance between debt and equity',
    trend: 'improving',
  },
  {
    id: 'customer_acquisition_cost',
    name: 'Customer Acquisition Cost',
    value: 45.2,
    status: 'warning',
    recommendation: 'Focus on organic growth channels',
    trend: 'stable',
  },
  {
    id: 'churn_rate',
    name: 'Customer Churn Rate',
    value: 3.2,
    status: 'healthy',
    recommendation: 'Continue current retention strategies',
    trend: 'improving',
  },
  {
    id: 'monthly_burn_rate',
    name: 'Monthly Burn Rate',
    value: 78500,
    status: 'warning',
    recommendation: 'Monitor operational expenses closely',
    trend: 'stable',
  },
]

export const revenueBreakdown: RevenueBreakdown[] = [
  {
    name: 'Transaction Fees',
    amount: 67500,
    percentage: 53.0,
    change: 12.5,
    color: '#3b82f6',
  },
  {
    name: 'Subscription Revenue',
    amount: 38250,
    percentage: 30.0,
    change: 8.2,
    color: '#10b981',
  },
  {
    name: 'Premium Features',
    amount: 15300,
    percentage: 12.0,
    change: 24.7,
    color: '#f59e0b',
  },
  {
    name: 'Consulting Services',
    amount: 6450,
    percentage: 5.0,
    change: -5.3,
    color: '#ef4444',
  },
]

export const expenseCategories: ExpenseCategory[] = [
  {
    name: 'Staff Salaries',
    amount: 45000,
    percentage: 35.2,
    budget: 50000,
    color: '#3b82f6',
  },
  {
    name: 'Technology & Infrastructure',
    amount: 22500,
    percentage: 17.6,
    budget: 25000,
    color: '#10b981',
  },
  {
    name: 'Marketing & Advertising',
    amount: 18750,
    percentage: 14.7,
    budget: 20000,
    color: '#f59e0b',
  },
  {
    name: 'Operations',
    amount: 15200,
    percentage: 11.9,
    budget: 18000,
    color: '#ef4444',
  },
  {
    name: 'Legal & Compliance',
    amount: 12800,
    percentage: 10.0,
    budget: 15000,
    color: '#8b5cf6',
  },
  {
    name: 'Office & Utilities',
    amount: 8950,
    percentage: 7.0,
    budget: 10000,
    color: '#06b6d4',
  },
  {
    name: 'Other',
    amount: 4800,
    percentage: 3.8,
    budget: 7000,
    color: '#6b7280',
  },
]

export const profitMarginData: ProfitMarginData[] = [
  {
    name: 'Jan',
    revenue: 142000,
    costs: 89000,
    grossProfit: 53000,
    margin: 37.3,
    date: '2024-01-01',
  },
  {
    name: 'Feb',
    revenue: 158000,
    costs: 94000,
    grossProfit: 64000,
    margin: 40.5,
    date: '2024-02-01',
  },
  {
    name: 'Mar',
    revenue: 135000,
    costs: 91000,
    grossProfit: 44000,
    margin: 32.6,
    date: '2024-03-01',
  },
  {
    name: 'Apr',
    revenue: 167000,
    costs: 98000,
    grossProfit: 69000,
    margin: 41.3,
    date: '2024-04-01',
  },
  {
    name: 'May',
    revenue: 149000,
    costs: 102000,
    grossProfit: 47000,
    margin: 31.5,
    date: '2024-05-01',
  },
  {
    name: 'Jun',
    revenue: 175000,
    costs: 108000,
    grossProfit: 67000,
    margin: 38.3,
    date: '2024-06-01',
  },
]

// Additional chart data for financial analytics
export const monthlyRevenueGrowth: ChartData[] = [
  { name: 'Jan', value: 142000 },
  { name: 'Feb', value: 158000 },
  { name: 'Mar', value: 135000 },
  { name: 'Apr', value: 167000 },
  { name: 'May', value: 149000 },
  { name: 'Jun', value: 175000 },
]

export const businessOnboardingTrend: ChartData[] = [
  { name: 'Jan', value: 1245 },
  { name: 'Feb', value: 1389 },
  { name: 'Mar', value: 1156 },
  { name: 'Apr', value: 1567 },
  { name: 'May', value: 1423 },
  { name: 'Jun', value: 1847 },
]

export const customerAcquisitionCost: ChartData[] = [
  { name: 'Jan', value: 52.3 },
  { name: 'Feb', value: 48.7 },
  { name: 'Mar', value: 51.2 },
  { name: 'Apr', value: 43.8 },
  { name: 'May', value: 46.5 },
  { name: 'Jun', value: 45.2 },
]

// Open Finance & Banking Integration Mock Data
export const bankAccounts: BankAccount[] = [
  {
    id: 'acc_001',
    bankName: 'Maybank',
    bankCode: 'MBB',
    accountNumber: '1234567890',
    accountType: 'business',
    balance: 285750.50,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-06-20T10:30:00Z',
    iban: 'MY7701234567890123456789',
    swiftCode: 'MBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_002',
    bankName: 'Public Bank',
    bankCode: 'PBB',
    accountNumber: '0987654321',
    accountType: 'savings',
    balance: 125800.75,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-06-20T10:25:00Z',
    iban: 'MY7702987654321098765432',
    swiftCode: 'PBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_003',
    bankName: 'CIMB Bank',
    bankCode: 'CIMB',
    accountNumber: '1122334455',
    accountType: 'checking',
    balance: 45200.25,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-06-20T10:20:00Z',
    iban: 'MY7703112233445566778899',
    swiftCode: 'CIBBMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_004',
    bankName: 'Hong Leong Bank',
    bankCode: 'HLB',
    accountNumber: '6677889900',
    accountType: 'credit',
    balance: -12500.00,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-06-20T10:15:00Z',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
]

export const transactions: Transaction[] = [
  {
    id: 'txn_001',
    accountId: 'acc_001',
    amount: 2500.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Product Sales',
    description: 'Payment from ABC Trading Sdn Bhd',
    counterpartyName: 'ABC Trading Sdn Bhd',
    counterpartyAccount: '1234567890',
    date: '2024-06-20',
    timestamp: '2024-06-20T09:30:00Z',
    reference: 'INV-2024-001',
    status: 'completed',
    balance: 285750.50,
    isRecurring: false,
    tags: ['income', 'b2b'],
    notes: 'Monthly supply payment',
  },
  {
    id: 'txn_002',
    accountId: 'acc_001',
    amount: -850.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Operating Expenses',
    subcategory: 'Utilities',
    description: 'TNB Electricity Bill',
    counterpartyName: 'Tenaga Nasional Berhad',
    date: '2024-06-19',
    timestamp: '2024-06-19T14:15:00Z',
    reference: 'TNB-202406-001',
    mcc: 4900,
    status: 'completed',
    balance: 283250.50,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['utilities', 'fixed_cost'],
  },
  {
    id: 'txn_003',
    accountId: 'acc_002',
    amount: 1200.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Service Revenue',
    description: 'Consulting service payment',
    counterpartyName: 'XYZ Enterprise',
    date: '2024-06-18',
    timestamp: '2024-06-18T16:45:00Z',
    reference: 'SRV-2024-025',
    status: 'completed',
    balance: 125800.75,
    isRecurring: false,
    tags: ['service', 'consulting'],
  },
  {
    id: 'txn_004',
    accountId: 'acc_001',
    amount: -350.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Operating Expenses',
    subcategory: 'Office Supplies',
    description: 'Office supplies purchase',
    counterpartyName: 'Office Depot Malaysia',
    date: '2024-06-17',
    timestamp: '2024-06-17T11:20:00Z',
    mcc: 5943,
    status: 'completed',
    balance: 282900.50,
    isRecurring: false,
    tags: ['supplies', 'office'],
  },
  {
    id: 'txn_005',
    accountId: 'acc_003',
    amount: -1500.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Staff Expenses',
    subcategory: 'Salaries',
    description: 'Staff salary payment',
    counterpartyName: 'Employee Payroll',
    date: '2024-06-15',
    timestamp: '2024-06-15T09:00:00Z',
    status: 'completed',
    balance: 45200.25,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['payroll', 'staff'],
  },
]

export const paymentMethods: PaymentMethod[] = [
  {
    id: 'pm_001',
    type: 'qr_code',
    provider: 'DuitNow QR',
    accountId: 'acc_001',
    isDefault: true,
    status: 'active',
    metadata: {
      qrCodeId: 'DN-QR-001',
      merchantId: 'MERCHANT-001',
      displayName: 'BizzKu Store',
    },
  },
  {
    id: 'pm_002',
    type: 'bank_transfer',
    provider: 'Maybank',
    accountId: 'acc_001',
    isDefault: false,
    status: 'active',
    metadata: {
      accountName: 'BizzKu Sdn Bhd',
      accountNumber: '1234567890',
      swiftCode: 'MBBEMYKL',
    },
  },
  {
    id: 'pm_003',
    type: 'digital_wallet',
    provider: 'GrabPay',
    isDefault: false,
    status: 'active',
    metadata: {
      walletId: 'GRAB-WALLET-001',
      merchantCode: 'GRAB-MERCHANT-001',
    },
  },
  {
    id: 'pm_004',
    type: 'card',
    provider: 'Visa',
    accountId: 'acc_004',
    isDefault: false,
    status: 'active',
    metadata: {
      cardNumber: '4111-****-****-1111',
      expiryDate: '12/26',
      cardType: 'business',
    },
  },
]

export const qrPayments: QRPayment[] = [
  {
    id: 'qr_001',
    merchantId: 'MERCHANT-001',
    amount: 25.50,
    currency: 'MYR',
    description: 'Coffee and pastry',
    expiryTime: '2024-06-20T18:00:00Z',
    isReusable: false,
    qrCodeData: 'duitnow://pay?amount=25.50&merchant=MERCHANT-001&ref=QR-001',
    qrCodeImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
    status: 'active',
    createdAt: '2024-06-20T09:30:00Z',
  },
  {
    id: 'qr_002',
    merchantId: 'MERCHANT-001',
    currency: 'MYR',
    description: 'General payment',
    isReusable: true,
    qrCodeData: 'duitnow://pay?merchant=MERCHANT-001&ref=QR-002',
    qrCodeImage: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==',
    status: 'active',
    createdAt: '2024-06-15T10:00:00Z',
  },
]

export const openFinanceConnections: OpenFinanceConnection[] = [
  {
    id: 'conn_001',
    providerId: 'maybank',
    providerName: 'Maybank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [bankAccounts[0]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:30:00Z',
    lastSyncTime: '2024-06-20T10:30:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'maybank-conn-001',
    },
  },
  {
    id: 'conn_002',
    providerId: 'publicbank',
    providerName: 'Public Bank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [bankAccounts[1]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:25:00Z',
    lastSyncTime: '2024-06-20T10:25:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'publicbank-conn-001',
    },
  },
  {
    id: 'conn_003',
    providerId: 'duitnow',
    providerName: 'DuitNow',
    connectionType: 'payment_service',
    status: 'connected',
    accounts: [],
    permissions: ['read_payments', 'create_qr', 'read_qr_status'],
    consentExpiryDate: '2024-12-20T10:00:00Z',
    lastSyncTime: '2024-06-20T10:00:00Z',
    metadata: {
      apiVersion: '3.0',
      merchantId: 'MERCHANT-001',
    },
  },
]

// Master-Detail Dashboard Mock Data
export const consolidatedFinancialData: ConsolidatedFinancialData = {
  totalBalance: 444251.50,
  totalIncome: 45750.00,
  totalExpenses: 28950.00,
  netCashFlow: 16800.00,
  accountsCount: 4,
  transactionsCount: 156,
  lastUpdated: '2024-06-20T10:30:00Z',
  currency: 'MYR',
  performanceMetrics: {
    monthlyGrowth: 12.5,
    expenseRatio: 0.63,
    savingsRate: 0.37,
    liquidityRatio: 2.8,
  },
}

export const transactionCategories: TransactionCategory[] = [
  {
    id: 'cat_001',
    name: 'Sales Revenue',
    type: 'income',
    color: '#10b981',
    icon: 'DollarSign',
    totalAmount: 28500.00,
    transactionCount: 45,
    percentage: 62.3,
    budget: 30000.00,
    trend: 'up',
    trendPercentage: 8.5,
  },
  {
    id: 'cat_002',
    name: 'Service Revenue',
    type: 'income',
    color: '#3b82f6',
    icon: 'Briefcase',
    totalAmount: 12250.00,
    transactionCount: 18,
    percentage: 26.8,
    budget: 15000.00,
    trend: 'up',
    trendPercentage: 12.3,
  },
  {
    id: 'cat_003',
    name: 'Investment Income',
    type: 'income',
    color: '#8b5cf6',
    icon: 'TrendingUp',
    totalAmount: 5000.00,
    transactionCount: 3,
    percentage: 10.9,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_004',
    name: 'Operating Expenses',
    type: 'expense',
    color: '#ef4444',
    icon: 'Settings',
    totalAmount: -15800.00,
    transactionCount: 32,
    percentage: 54.6,
    budget: 18000.00,
    trend: 'down',
    trendPercentage: -5.2,
  },
  {
    id: 'cat_005',
    name: 'Staff Expenses',
    type: 'expense',
    color: '#f59e0b',
    icon: 'Users',
    totalAmount: -8500.00,
    transactionCount: 12,
    percentage: 29.4,
    budget: 10000.00,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_006',
    name: 'Marketing',
    type: 'expense',
    color: '#06b6d4',
    icon: 'Briefcase',
    totalAmount: -3200.00,
    transactionCount: 8,
    percentage: 11.1,
    budget: 5000.00,
    trend: 'up',
    trendPercentage: 15.8,
  },
  {
    id: 'cat_007',
    name: 'Office Supplies',
    type: 'expense',
    color: '#84cc16',
    icon: 'FileText',
    totalAmount: -1450.00,
    transactionCount: 15,
    percentage: 5.0,
    budget: 2000.00,
    trend: 'down',
    trendPercentage: -8.3,
  },
]

export const supplierCustomerData: SupplierCustomerData[] = [
  {
    id: 'sc_001',
    name: 'ABC Trading Sdn Bhd',
    type: 'customer',
    totalTransactions: 24,
    totalAmount: 48500.00,
    averageTransaction: 2020.83,
    lastTransactionDate: '2024-06-20',
    paymentTerms: 'Net 30',
    creditLimit: 50000.00,
    outstandingBalance: 8500.00,
    contactInfo: {
      email: 'accounts@abctrading.com.my',
      phone: '+603-1234-5678',
      address: '123 Business Park, Kuala Lumpur',
      taxId: 'GST-123456789',
    },
    relationshipScore: 85,
    riskAssessment: 'low',
  },
  {
    id: 'sc_002',
    name: 'XYZ Enterprise',
    type: 'customer',
    totalTransactions: 18,
    totalAmount: 32800.00,
    averageTransaction: 1822.22,
    lastTransactionDate: '2024-06-18',
    paymentTerms: 'Net 15',
    creditLimit: 35000.00,
    outstandingBalance: 5200.00,
    contactInfo: {
      email: 'billing@xyzenterprise.com',
      phone: '+603-9876-5432',
      address: '456 Commerce Ave, Petaling Jaya',
      taxId: 'GST-987654321',
    },
    relationshipScore: 78,
    riskAssessment: 'low',
  },
  {
    id: 'sc_003',
    name: 'Global Supplies Ltd',
    type: 'supplier',
    totalTransactions: 32,
    totalAmount: -25600.00,
    averageTransaction: -800.00,
    lastTransactionDate: '2024-06-19',
    paymentTerms: 'Net 30',
    creditLimit: 30000.00,
    outstandingBalance: -12500.00,
    contactInfo: {
      email: 'sales@globalsupplies.com',
      phone: '+603-5555-1234',
      address: '789 Supply Chain Blvd, Shah Alam',
      taxId: 'GST-456789123',
    },
    relationshipScore: 92,
    riskAssessment: 'low',
  },
  {
    id: 'sc_004',
    name: 'Tech Solutions Provider',
    type: 'supplier',
    totalTransactions: 8,
    totalAmount: -18400.00,
    averageTransaction: -2300.00,
    lastTransactionDate: '2024-06-15',
    paymentTerms: 'Net 45',
    creditLimit: 25000.00,
    outstandingBalance: -4800.00,
    contactInfo: {
      email: 'invoices@techsolutions.com.my',
      phone: '+603-7777-8888',
      address: '321 Tech Park, Cyberjaya',
      taxId: 'GST-789123456',
    },
    relationshipScore: 68,
    riskAssessment: 'medium',
  },
  {
    id: 'sc_005',
    name: 'Logistics Partners Sdn Bhd',
    type: 'supplier',
    totalTransactions: 45,
    totalAmount: -15800.00,
    averageTransaction: -351.11,
    lastTransactionDate: '2024-06-20',
    paymentTerms: 'Net 15',
    creditLimit: 20000.00,
    outstandingBalance: -2300.00,
    contactInfo: {
      email: 'billing@logisticspartners.com',
      phone: '+603-3333-4444',
      address: '654 Logistics Hub, Port Klang',
      taxId: 'GST-321654987',
    },
    relationshipScore: 88,
    riskAssessment: 'low',
  },
]

// Compliance & Reporting Mock Data
export const complianceReports: ComplianceReport[] = [
  {
    id: 'cr_001',
    type: 'tax',
    period: 'Q2 2024',
    status: 'submitted',
    data: {
      grossIncome: 182500.00,
      deductions: 54750.00,
      taxableIncome: 127750.00,
      taxOwed: 12775.00,
    },
    generatedAt: '2024-06-15T09:00:00Z',
    submittedAt: '2024-06-18T16:30:00Z',
    dueDate: '2024-07-31T23:59:59Z',
    requirements: [
      'Quarterly GST return',
      'Income tax estimation',
      'Payroll tax summary',
    ],
    attachments: [
      'GST-F1-Q2-2024.pdf',
      'Income-Tax-Q2-2024.pdf',
      'Payroll-Summary-Q2-2024.pdf',
    ],
  },
  {
    id: 'cr_002',
    type: 'financial',
    period: 'May 2024',
    status: 'approved',
    data: {
      revenue: 45750.00,
      expenses: 28950.00,
      netIncome: 16800.00,
      assets: 444251.50,
      liabilities: 125600.00,
    },
    generatedAt: '2024-06-01T10:00:00Z',
    submittedAt: '2024-06-05T14:20:00Z',
    dueDate: '2024-06-15T23:59:59Z',
    requirements: [
      'Monthly financial statement',
      'Balance sheet',
      'Cash flow statement',
    ],
    attachments: [
      'Financial-Statement-May-2024.pdf',
      'Balance-Sheet-May-2024.pdf',
      'Cash-Flow-Statement-May-2024.pdf',
    ],
  },
]

export const taxCalculation: TaxCalculation = {
  grossIncome: 182500.00,
  deductions: 54750.00,
  taxableIncome: 127750.00,
  taxOwed: 12775.00,
  taxRate: 10.0,
  estimatedQuarterly: 3193.75,
  lastCalculated: '2024-06-20T10:30:00Z',
  breakdown: {
    incomeTax: 8975.00,
    salesTax: 2280.00,
    payrollTax: 1520.00,
    otherTaxes: 0.00,
  },
}

// Invoice Management Mock Data
export const invoices: Invoice[] = [
  {
    id: 'inv_001',
    number: 'INV-2024-001',
    type: 'sent',
    customerId: 'sc_001',
    amount: 2500.00,
    currency: 'MYR',
    status: 'paid',
    issueDate: '2024-05-20',
    dueDate: '2024-06-19',
    paidDate: '2024-06-20',
    description: 'Monthly supply of products',
    items: [
      {
        id: 'item_001',
        description: 'Product A',
        quantity: 50,
        unitPrice: 25.00,
        totalPrice: 1250.00,
        taxRate: 6.0,
        category: 'Products',
      },
      {
        id: 'item_002',
        description: 'Product B',
        quantity: 25,
        unitPrice: 40.00,
        totalPrice: 1000.00,
        taxRate: 6.0,
        category: 'Products',
      },
    ],
    taxAmount: 135.00,
    totalAmount: 2385.00,
    paymentTerms: 'Net 30',
    notes: 'Thank you for your business',
    attachments: ['INV-2024-001.pdf'],
  },
  {
    id: 'inv_002',
    number: 'INV-2024-002',
    type: 'sent',
    customerId: 'sc_002',
    amount: 1200.00,
    currency: 'MYR',
    status: 'sent',
    issueDate: '2024-06-10',
    dueDate: '2024-06-25',
    description: 'Consulting services',
    items: [
      {
        id: 'item_003',
        description: 'Business consultation',
        quantity: 8,
        unitPrice: 150.00,
        totalPrice: 1200.00,
        taxRate: 6.0,
        category: 'Services',
      },
    ],
    taxAmount: 72.00,
    totalAmount: 1272.00,
    paymentTerms: 'Net 15',
    notes: 'Please remit payment within 15 days',
    attachments: ['INV-2024-002.pdf'],
  },
  {
    id: 'inv_003',
    number: 'PO-2024-001',
    type: 'received',
    supplierId: 'sc_003',
    amount: 3200.00,
    currency: 'MYR',
    status: 'paid',
    issueDate: '2024-06-05',
    dueDate: '2024-07-05',
    paidDate: '2024-06-19',
    description: 'Office supplies and equipment',
    items: [
      {
        id: 'item_004',
        description: 'Office chairs',
        quantity: 5,
        unitPrice: 400.00,
        totalPrice: 2000.00,
        taxRate: 6.0,
        category: 'Office Equipment',
      },
      {
        id: 'item_005',
        description: 'Desk supplies',
        quantity: 1,
        unitPrice: 1200.00,
        totalPrice: 1200.00,
        taxRate: 6.0,
        category: 'Office Supplies',
      },
    ],
    taxAmount: 192.00,
    totalAmount: 3392.00,
    paymentTerms: 'Net 30',
    attachments: ['PO-2024-001.pdf'],
  },
]

// Multi-language Support Mock Data
export const languageSupport: LanguageSupport[] = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    isRTL: false,
    flag: '🇺🇸',
    isActive: true,
    completionPercentage: 100,
  },
  {
    code: 'ms',
    name: 'Malay',
    nativeName: 'Bahasa Malaysia',
    isRTL: false,
    flag: '🇲🇾',
    isActive: true,
    completionPercentage: 95,
  },
  {
    code: 'zh',
    name: 'Chinese',
    nativeName: '中文',
    isRTL: false,
    flag: '🇨🇳',
    isActive: true,
    completionPercentage: 88,
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    isRTL: false,
    flag: '🇮🇳',
    isActive: true,
    completionPercentage: 82,
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    isRTL: false,
    flag: '🇮🇳',
    isActive: false,
    completionPercentage: 65,
  },
  {
    code: 'th',
    name: 'Thai',
    nativeName: 'ไทย',
    isRTL: false,
    flag: '🇹🇭',
    isActive: false,
    completionPercentage: 70,
  },
  {
    code: 'vi',
    name: 'Vietnamese',
    nativeName: 'Tiếng Việt',
    isRTL: false,
    flag: '🇻🇳',
    isActive: false,
    completionPercentage: 75,
  },
  {
    code: 'id',
    name: 'Indonesian',
    nativeName: 'Bahasa Indonesia',
    isRTL: false,
    flag: '🇮🇩',
    isActive: false,
    completionPercentage: 68,
  },
]
