import { 
  KPICard, 
  ChartData, 
  FinancialKPI,
  CashFlowData,
  BusinessMetrics,
  FinancialHealthIndicator,
  RevenueBreakdown,
  ExpenseCategory,
  ProfitMarginData,
  BankAccount,
  Transaction,
  QRPayment,
  OpenFinanceConnection,
  ConsolidatedFinancialData,
  TransactionCategory,
  SupplierCustomerData,
} from './types'
import { 
  Users, 
  TrendingUp, 
  Shield, 
  Zap, 
  Target, 
  Award, 
  Heart, 
  Globe,
  DollarSign,
  ShoppingCart,
  UserCheck,
  BarChart3,
  Building2,
  CreditCard,
  QrCode,
  ArrowUpDown,
  PieChart,
  FileText,
  Calculator,
  Receipt,
  Truck,
  Store,
  Coffee,
  Car,
  Home,
  Smartphone,
  Utensils,
  Briefcase,
  Fuel,
  Stethoscope,
  GraduationCap,
  Gamepad2,
  Plane,
  Gift,
  Shirt,
  Wrench,
  Zap as ElectricIcon,
  Wifi,
  Music,
  Film,
  Book,
  Dumbbell,
  Scissors,
  Paintbrush,
  Flower,
  ShieldCheck,
  AlertCircle,
  CheckCircle2,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe2,
  Languages,
  Calendar,
  FileCheck,
  TrendingDown,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Minus,
  Plus,
  Eye,
  EyeOff,
  Loader,
  RefreshCw,
  Download,
  Upload,
  Filter,
  Search,
  Settings,
  Bell,
  HelpCircle,
  LogOut,
  User,
  Edit,
  Trash,
  Copy,
  Share,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  MoreHorizontal,
  MoreVertical
} from 'lucide-react'

// Malaysian MSME Business Profile
export const msmeBusinessProfile = {
  name: "Warung Nasi Lemak Kak Siti",
  owner: "Siti Aminah binti Abdullah",
  businessType: "Food & Beverage",
  category: "Traditional Malaysian Cuisine",
  established: "2019",
  location: "Taman Melawati, Kuala Lumpur",
  employees: 3,
  operatingHours: "7:00 AM - 2:00 PM",
  businessRegistration: "SA0123456789",
  gstNumber: "000123456789",
  description: "Traditional Malaysian nasi lemak stall serving authentic homemade recipes passed down through generations",
  specialties: ["Nasi Lemak", "Ayam Rendang", "Sambal Ikan Bilis", "Telur Dadar", "Acar Timun"],
  dailyCapacity: 150,
  averageOrderValue: 8.50,
  paymentMethods: ["Cash", "DuitNow QR", "Touch 'n Go eWallet", "GrabPay", "Maybank QRPay"]
}

// Malaysian MSME KPI Data - PAYMENT-CENTRIC VERSION
export const msmeKPIData: KPICard[] = [
  {
    id: '1',
    title: 'Monthly Cash Inflow',
    value: 'RM 18,750',
    change: 15.2,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Total money received from all payment methods',
  },
  {
    id: '2',
    title: 'Daily Transactions',
    value: '47',
    change: 8.7,
    changeType: 'increase',
    icon: ArrowUpDown,
    description: 'Average number of transactions per day',
  },
  {
    id: '3',
    title: 'Cash Flow Health',
    value: '87%',
    change: 2.3,
    changeType: 'increase',
    icon: TrendingUp,
    description: 'Positive cash flow ratio',
  },
  {
    id: '4',
    title: 'Connected Banks',
    value: '3',
    change: 0,
    changeType: 'stable',
    icon: Building2,
    description: 'Active bank accounts',
  },
]

// Malaysian Banking Data - PAYMENT-CENTRIC VERSION
export const msmeFinancialKPIs: FinancialKPI[] = [
  {
    id: 'daily_inflow',
    title: 'Daily Cash Inflow',
    value: 'RM 1,125',
    change: 18.5,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Average daily money received',
    period: 'daily',
    currency: 'MYR',
    trend: 'up',
    target: 1200,
  },
  {
    id: 'monthly_outflow',
    title: 'Monthly Cash Outflow',
    value: 'RM 10,000',
    change: -5.2,
    changeType: 'decrease',
    icon: TrendingDown,
    description: 'Total monthly expenses paid',
    period: 'monthly',
    currency: 'MYR',
    trend: 'down',
    target: 9500,
  },
  {
    id: 'net_cash_flow',
    title: 'Net Cash Flow',
    value: 'RM 8,750',
    change: 22.3,
    changeType: 'increase',
    icon: BarChart3,
    description: 'Monthly net cash flow (inflow - outflow)',
    period: 'monthly',
    currency: 'MYR',
    trend: 'up',
    target: 9000,
  },
  {
    id: 'payment_frequency',
    title: 'Transaction Frequency',
    value: '47/day',
    change: 12.8,
    changeType: 'increase',
    icon: Clock,
    description: 'Average transactions per day',
    period: 'daily',
    trend: 'up',
    target: 50,
  },
  {
    id: 'digital_payments',
    title: 'Digital Payments',
    value: '76%',
    change: 31.2,
    changeType: 'increase',
    icon: QrCode,
    description: 'Non-cash payment percentage',
    period: 'monthly',
    trend: 'up',
    target: 80,
  },
  {
    id: 'cash_utilization',
    title: 'Cash Utilization',
    value: '68%',
    change: 2.1,
    changeType: 'increase',
    icon: PieChart,
    description: 'Percentage of available cash being used',
    period: 'monthly',
    trend: 'up',
    target: 70,
  },
]

// Malaysian Bank Accounts
export const msmeBankAccounts: BankAccount[] = [
  {
    id: 'acc_maybank_001',
    bankName: 'Maybank',
    bankCode: 'MBB',
    accountNumber: '1234567890',
    accountType: 'business',
    balance: 28750.50,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:30:00Z',
    iban: 'MY7701234567890123456789',
    swiftCode: 'MBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_publicbank_001',
    bankName: 'Public Bank',
    bankCode: 'PBB',
    accountNumber: '9876543210',
    accountType: 'savings',
    balance: 15800.75,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:25:00Z',
    iban: 'MY7702987654321098765432',
    swiftCode: 'PBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_cimb_001',
    bankName: 'CIMB Bank',
    bankCode: 'CIMB',
    accountNumber: '1122334455',
    accountType: 'checking',
    balance: 12200.25,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:20:00Z',
    iban: 'MY7703112233445566778899',
    swiftCode: 'CIBBMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
]

// Malaysian MSME Transactions
export const msmeTransactions: Transaction[] = [
  {
    id: 'txn_001',
    accountId: 'acc_maybank_001',
    amount: 850.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Nasi Lemak Sales',
    description: 'Daily sales - Nasi Lemak orders',
    counterpartyName: 'Cash & Digital Payments',
    date: '2024-01-20',
    timestamp: '2024-01-20T14:30:00Z',
    reference: 'DAILY-SALES-20240120',
    status: 'completed',
    balance: 28750.50,
    isRecurring: true,
    recurringPattern: 'daily',
    tags: ['food_sales', 'nasi_lemak', 'daily_revenue'],
    notes: 'Mixed payment methods: 60% digital, 40% cash',
  },
  {
    id: 'txn_002',
    accountId: 'acc_maybank_001',
    amount: -320.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Ingredients',
    subcategory: 'Fresh Ingredients',
    description: 'Pasar Borong Selayang - Rice, chicken, vegetables',
    counterpartyName: 'Pasar Borong Selayang',
    date: '2024-01-20',
    timestamp: '2024-01-20T06:15:00Z',
    reference: 'INGREDIENTS-20240120',
    status: 'completed',
    balance: 27900.50,
    isRecurring: true,
    recurringPattern: 'daily',
    tags: ['ingredients', 'market', 'cogs'],
    notes: 'Daily fresh ingredients purchase',
  },
  {
    id: 'txn_003',
    accountId: 'acc_publicbank_001',
    amount: 1200.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Catering Service',
    description: 'Office catering - Nasi Lemak for 50 pax',
    counterpartyName: 'ABC Consulting Sdn Bhd',
    date: '2024-01-19',
    timestamp: '2024-01-19T11:45:00Z',
    reference: 'CATERING-ABC-20240119',
    status: 'completed',
    balance: 15800.75,
    isRecurring: false,
    tags: ['catering', 'bulk_order', 'b2b'],
    notes: 'Special order for office lunch',
  },
  {
    id: 'txn_004',
    accountId: 'acc_maybank_001',
    amount: -180.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'TNB - Monthly electricity bill',
    counterpartyName: 'Tenaga Nasional Berhad',
    date: '2024-01-18',
    timestamp: '2024-01-18T09:20:00Z',
    reference: 'TNB-202401-001',
    status: 'completed',
    balance: 27720.50,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['utilities', 'fixed_cost', 'electricity'],
    notes: 'Stall electricity bill',
  },
  {
    id: 'txn_005',
    accountId: 'acc_cimb_001',
    amount: -450.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Staff',
    subcategory: 'Part-time Helper',
    description: 'Weekly salary - Aminah (kitchen helper)',
    counterpartyName: 'Aminah binti Yusof',
    date: '2024-01-17',
    timestamp: '2024-01-17T16:00:00Z',
    reference: 'SALARY-AMINAH-W3-2024',
    status: 'completed',
    balance: 12200.25,
    isRecurring: true,
    recurringPattern: 'weekly',
    tags: ['salary', 'part_time', 'staff'],
    notes: 'Kitchen helper - 30 hours/week',
  },
  {
    id: 'txn_006',
    accountId: 'acc_maybank_001',
    amount: -85.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Packaging',
    subcategory: 'Eco-friendly Containers',
    description: 'Biodegradable food containers and banana leaves',
    counterpartyName: 'Green Pack Malaysia',
    date: '2024-01-16',
    timestamp: '2024-01-16T13:30:00Z',
    reference: 'PACK-GREEN-20240116',
    status: 'completed',
    balance: 27635.50,
    isRecurring: true,
    recurringPattern: 'weekly',
    tags: ['packaging', 'eco_friendly', 'supplies'],
    notes: 'Sustainable packaging materials',
  },
  {
    id: 'txn_007',
    accountId: 'acc_publicbank_001',
    amount: 950.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Weekend Sales',
    description: 'Weekend high traffic - Nasi Lemak sales',
    counterpartyName: 'Weekend Customer Sales',
    date: '2024-01-15',
    timestamp: '2024-01-15T15:30:00Z',
    reference: 'WEEKEND-SALES-20240115',
    status: 'completed',
    balance: 14850.75,
    isRecurring: false,
    tags: ['weekend', 'high_traffic', 'sales'],
    notes: 'Weekend peak sales period',
  },
  {
    id: 'txn_008',
    accountId: 'acc_maybank_001',
    amount: -250.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Marketing',
    subcategory: 'Social Media',
    description: 'Facebook & Instagram ads promotion',
    counterpartyName: 'Meta Malaysia',
    date: '2024-01-14',
    timestamp: '2024-01-14T10:15:00Z',
    reference: 'META-ADS-20240114',
    status: 'completed',
    balance: 27385.50,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['marketing', 'social_media', 'ads'],
    notes: 'Monthly social media advertising',
  },
]

// Cash Flow Data for Malaysian MSME
export const msmeCashFlowData: CashFlowData[] = [
  {
    name: 'Week 1',
    date: '2024-01-07',
    income: 5950.00,
    expenses: 2280.00,
    netCashFlow: 3670.00,
    cumulativeCashFlow: 3670.00,
  },
  {
    name: 'Week 2',
    date: '2024-01-14',
    income: 6280.00,
    expenses: 2450.00,
    netCashFlow: 3830.00,
    cumulativeCashFlow: 7500.00,
  },
  {
    name: 'Week 3',
    date: '2024-01-21',
    income: 7120.00,
    expenses: 2680.00,
    netCashFlow: 4440.00,
    cumulativeCashFlow: 11940.00,
  },
  {
    name: 'Week 4',
    date: '2024-01-28',
    income: 6850.00,
    expenses: 2590.00,
    netCashFlow: 4260.00,
    cumulativeCashFlow: 16200.00,
  },
]

// Payment Method Breakdown - PAYMENT-CENTRIC VERSION
export const msmePaymentMethodBreakdown: RevenueBreakdown[] = [
  {
    name: 'DuitNow QR',
    amount: 8475.00,
    percentage: 45.2,
    change: 31.2,
    color: '#22c55e',
    description: 'DuitNow QR code payments',
  },
  {
    name: 'Touch \'n Go eWallet',
    amount: 5231.25,
    percentage: 27.9,
    change: 18.5,
    color: '#3b82f6',
    description: 'Touch \'n Go digital wallet payments',
  },
  {
    name: 'GrabPay',
    amount: 3243.75,
    percentage: 17.3,
    change: 25.8,
    color: '#f59e0b',
    description: 'GrabPay digital payments',
  },
  {
    name: 'Cash Payments',
    amount: 1856.25,
    percentage: 9.9,
    change: -12.3,
    color: '#ef4444',
    description: 'Traditional cash payments',
  },
]

// Keep the same variable name for backward compatibility
export const msmeRevenueBreakdown = msmePaymentMethodBreakdown

// Expense Categories for Malaysian MSME
export const msmeExpenseCategories: ExpenseCategory[] = [
  {
    name: 'Ingredients & Raw Materials',
    amount: 6000.00,
    percentage: 60.0,
    budget: 6500.00,
    color: '#ef4444',
  },
  {
    name: 'Staff Wages',
    amount: 1800.00,
    percentage: 18.0,
    budget: 2000.00,
    color: '#3b82f6',
  },
  {
    name: 'Utilities (Electricity, Water)',
    amount: 720.00,
    percentage: 7.2,
    budget: 800.00,
    color: '#f59e0b',
  },
  {
    name: 'Packaging & Supplies',
    amount: 600.00,
    percentage: 6.0,
    budget: 700.00,
    color: '#10b981',
  },
  {
    name: 'Stall Rent',
    amount: 500.00,
    percentage: 5.0,
    budget: 500.00,
    color: '#8b5cf6',
  },
  {
    name: 'Marketing & Promotion',
    amount: 250.00,
    percentage: 2.5,
    budget: 300.00,
    color: '#06b6d4',
  },
  {
    name: 'Transportation',
    amount: 130.00,
    percentage: 1.3,
    budget: 200.00,
    color: '#84cc16',
  },
]

// Monthly Cash Flow Growth - PAYMENT-CENTRIC VERSION
export const msmeMonthlyRevenueGrowth: ChartData[] = [
  { name: 'Jul', value: 7200.00 },
  { name: 'Aug', value: 7800.00 },
  { name: 'Sep', value: 8100.00 },
  { name: 'Oct', value: 8400.00 },
  { name: 'Nov', value: 8600.00 },
  { name: 'Dec', value: 8750.00 },
]

// Daily Cash Flow Pattern - PAYMENT-CENTRIC VERSION
export const msmeDailyCashFlowPattern: ChartData[] = [
  { name: 'Mon', value: 680.00 },
  { name: 'Tue', value: 750.00 },
  { name: 'Wed', value: 820.00 },
  { name: 'Thu', value: 950.00 },
  { name: 'Fri', value: 1080.00 },
  { name: 'Sat', value: 1320.00 },
  { name: 'Sun', value: 1200.00 },
]

// Keep the same variable name for backward compatibility
export const msmeDailySalesPattern = msmeDailyCashFlowPattern

// QR Payment Methods
export const msmeQRPayments: QRPayment[] = [
  {
    id: 'qr_duitnow_001',
    type: 'duitnow',
    amount: 0,
    currency: 'MYR',
    description: 'Warung Nasi Lemak Kak Siti - General Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 847,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'MY7701234567890',
  },
  {
    id: 'qr_touchngo_001',
    type: 'touchngo',
    amount: 0,
    currency: 'MYR',
    description: 'Touch n Go eWallet - Nasi Lemak Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 523,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'TNG-MSME-001',
  },
  {
    id: 'qr_grabpay_001',
    type: 'grabpay',
    amount: 0,
    currency: 'MYR',
    description: 'GrabPay - Food Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 324,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'GRAB-MSME-001',
  },
]

// Open Finance Connections
export const msmeOpenFinanceConnections: OpenFinanceConnection[] = [
  {
    id: 'conn_maybank_001',
    providerId: 'maybank',
    providerName: 'Maybank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [msmeBankAccounts[0]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:30:00Z',
    lastSyncTime: '2024-01-20T10:30:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'maybank-msme-001',
    },
  },
  {
    id: 'conn_publicbank_001',
    providerId: 'publicbank',
    providerName: 'Public Bank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [msmeBankAccounts[1]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:25:00Z',
    lastSyncTime: '2024-01-20T10:25:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'publicbank-msme-001',
    },
  },
  {
    id: 'conn_duitnow_001',
    providerId: 'duitnow',
    providerName: 'DuitNow',
    connectionType: 'payment_service',
    status: 'connected',
    accounts: [],
    permissions: ['read_payments', 'create_qr', 'read_qr_status'],
    consentExpiryDate: '2024-12-20T10:00:00Z',
    lastSyncTime: '2024-01-20T10:00:00Z',
    metadata: {
      apiVersion: '3.0',
      merchantId: 'DUITNOW-MSME-001',
    },
  },
  {
    id: 'conn_shopee_001',
    providerId: 'shopee',
    providerName: 'Shopee',
    connectionType: 'e-commerce',
    status: 'connected',
    accounts: [],
    permissions: ['read_sales', 'read_orders', 'read_payments', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:00:00Z',
    lastSyncTime: '2024-01-20T10:00:00Z',
    metadata: {
      apiVersion: '2.1',
      merchantId: 'SHOPEE-MSME-001',
      storeBalance: 8450.75,
    },
  },
]

// Consolidated Financial Data
export const msmeConsolidatedFinancialData: ConsolidatedFinancialData = {
  totalBalance: 65202.25,
  totalIncome: 18750.00,
  totalExpenses: 10000.00,
  netCashFlow: 8750.00,
  accountsCount: 4,
  transactionsCount: 350,
  lastUpdated: '2024-01-20T10:30:00Z',
  currency: 'MYR',
  performanceMetrics: {
    monthlyGrowth: 15.2,
    expenseRatio: 0.53,
    savingsRate: 0.47,
    liquidityRatio: 5.7,
  },
  creditScore: {
    currentScore: 720,
    scoreRange: { min: 300, max: 850 },
    grade: 'B+',
    trend: 'improving',
    monthlyChange: 15,
    lastUpdated: '2024-01-20T10:30:00Z',
    factors: [
      {
        id: 'payment_history',
        name: 'Payment History',
        weight: 45,
        score: 85,
        status: 'healthy',
        trend: 'stable',
        impact: 'high',
        recommendation: 'Continue paying bills on time. Late payments (30+ days) significantly hurt your score. Avoid collections, settlements, or legal judgments.'
      },
      {
        id: 'amounts_owed',
        name: 'Amounts Owed',
        weight: 20,
        score: 72,
        status: 'warning',
        trend: 'declining',
        impact: 'high',
        recommendation: 'Reduce total credit utilization below 30%. Maintain a good mix of credit types and pay down existing balances to improve this factor.'
      },
      {
        id: 'length_of_credit_history',
        name: 'Length of Credit History',
        weight: 7,
        score: 92,
        status: 'healthy',
        trend: 'stable',
        impact: 'low',
        recommendation: 'Your established credit history is excellent. Keep older accounts open to maintain your average account age and credit history length.'
      },
      {
        id: 'credit_mix',
        name: 'Credit Mix',
        weight: 14,
        score: 78,
        status: 'healthy',
        trend: 'improving',
        impact: 'medium',
        recommendation: 'Good variety of credit types (credit cards, loans, trade credit). Maintain responsible management across all account types.'
      },
      {
        id: 'new_credit',
        name: 'New Credit',
        weight: 14,
        score: 68,
        status: 'warning',
        trend: 'declining',
        impact: 'medium',
        recommendation: 'Limit new credit applications. Recent credit inquiries and new accounts suggest higher risk. Space out credit applications over time.'
      }
    ]
  },
  businessHealth: {
    overallHealth: 'good',
    healthScore: 76,
    keyStrengths: [
      'Excellent payment history with no late payments',
      'Long-established credit history (8+ years)',
      'Diverse credit mix across multiple account types',
      'Strong relationship with financial institutions'
    ],
    improvementAreas: [
      'Total amounts owed across credit facilities',
      'Recent new credit applications', 
      'Credit utilization ratio optimization',
      'Debt-to-income ratio management'
    ],
    recommendedActions: [
      'Reduce total debt balances to improve amounts owed ratio',
      'Limit new credit applications to avoid negative impact',
      'Maintain timely payments across all credit accounts',
      'Keep older credit accounts open to preserve credit history length',
      'Diversify credit mix responsibly without overextending'
    ],
    riskFactors: [
      'High total debt levels affecting amounts owed score',
      'Recent credit inquiries showing increased credit-seeking behavior',
      'Concentration of debt in single credit facility type'
    ]
  }
}

// Transaction Categories - PAYMENT-CENTRIC VERSION
export const msmeTransactionCategories: TransactionCategory[] = [
  {
    id: 'cat_inflow',
    name: 'Payment Inflow',
    type: 'income',
    color: '#22c55e',
    icon: 'ArrowUpRight',
    totalAmount: 16500.00,
    transactionCount: 98,
    percentage: 88.0,
    budget: 18000.00,
    trend: 'up',
    trendPercentage: 15.2,
  },
  {
    id: 'cat_bulk_payments',
    name: 'Large Payments',
    type: 'income',
    color: '#3b82f6',
    icon: 'DollarSign',
    totalAmount: 2250.00,
    transactionCount: 8,
    percentage: 12.0,
    budget: 2500.00,
    trend: 'up',
    trendPercentage: 25.6,
  },
  {
    id: 'cat_ingredients',
    name: 'Ingredients',
    type: 'expense',
    color: '#ef4444',
    icon: 'ShoppingCart',
    totalAmount: -6000.00,
    transactionCount: 28,
    percentage: 60.0,
    budget: 6500.00,
    trend: 'down',
    trendPercentage: -5.2,
  },
  {
    id: 'cat_staff',
    name: 'Staff Wages',
    type: 'expense',
    color: '#f59e0b',
    icon: 'Users',
    totalAmount: -1800.00,
    transactionCount: 12,
    percentage: 18.0,
    budget: 2000.00,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_utilities',
    name: 'Utilities',
    type: 'expense',
    color: '#8b5cf6',
    icon: 'Zap',
    totalAmount: -720.00,
    transactionCount: 6,
    percentage: 7.2,
    budget: 800.00,
    trend: 'down',
    trendPercentage: -8.3,
  },
  {
    id: 'cat_supplies',
    name: 'Supplies & Packaging',
    type: 'expense',
    color: '#06b6d4',
    icon: 'Package',
    totalAmount: -600.00,
    transactionCount: 8,
    percentage: 6.0,
    budget: 700.00,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_marketing',
    name: 'Marketing',
    type: 'expense',
    color: '#84cc16',
    icon: 'Megaphone',
    totalAmount: -250.00,
    transactionCount: 4,
    percentage: 2.5,
    budget: 300.00,
    trend: 'up',
    trendPercentage: 12.5,
  },
]

// Financial Health Indicators
export const msmeFinancialHealthIndicators: FinancialHealthIndicator[] = [
  {
    id: 'liquidity_ratio',
    name: 'Liquidity Ratio',
    value: 5.7,
    status: 'healthy',
    recommendation: 'Strong cash position for daily operations',
    trend: 'stable',
  },
  {
    id: 'profit_margin',
    name: 'Profit Margin',
    value: 68.0,
    status: 'healthy',
    recommendation: 'Excellent profit margins for food business',
    trend: 'improving',
  },
  {
    id: 'ingredient_cost_ratio',
    name: 'Ingredient Cost Ratio',
    value: 32.0,
    status: 'healthy',
    recommendation: 'Well-controlled ingredient costs',
    trend: 'stable',
  },
  {
    id: 'digital_payment_adoption',
    name: 'Digital Payment Adoption',
    value: 76.0,
    status: 'healthy',
    recommendation: 'Good digital payment integration',
    trend: 'improving',
  },
  {
    id: 'daily_sales_consistency',
    name: 'Sales Consistency',
    value: 89.0,
    status: 'healthy',
    recommendation: 'Stable daily sales performance',
    trend: 'stable',
  },
]

// Business Growth Metrics
export const msmeBusinessGrowthMetrics: BusinessMetrics[] = [
  {
    id: 'customer_retention',
    name: 'Customer Retention',
    completionRate: 85.2,
    averageTime: 0,
    dropOffRate: 14.8,
    satisfactionScore: 4.8,
    date: '2024-01-20',
  },
  {
    id: 'order_frequency',
    name: 'Order Frequency',
    completionRate: 92.1,
    averageTime: 0,
    dropOffRate: 7.9,
    satisfactionScore: 4.6,
    date: '2024-01-20',
  },
  {
    id: 'digital_adoption',
    name: 'Digital Payment Adoption',
    completionRate: 76.0,
    averageTime: 0,
    dropOffRate: 24.0,
    satisfactionScore: 4.2,
    date: '2024-01-20',
  },
  {
    id: 'operational_efficiency',
    name: 'Operational Efficiency',
    completionRate: 88.5,
    averageTime: 0,
    dropOffRate: 11.5,
    satisfactionScore: 4.4,
    date: '2024-01-20',
  },
]

// Payment Method Performance - PAYMENT-CENTRIC VERSION
export const msmePaymentMethodPerformance: ChartData[] = [
  { name: 'DuitNow QR', value: 847 },
  { name: 'Touch n Go', value: 523 },
  { name: 'GrabPay', value: 324 },
  { name: 'Shopee', value: 186 },
  { name: 'Bank Transfer', value: 92 },
  { name: 'Credit Card', value: 45 },
]

// Keep the same variable name for backward compatibility
export const msmeMenuPerformance = msmePaymentMethodPerformance

// Peak Payment Hours - PAYMENT-CENTRIC VERSION
export const msmePaymentPeakHours: ChartData[] = [
  { name: '7:00-8:00', value: 12 },
  { name: '8:00-9:00', value: 23 },
  { name: '9:00-10:00', value: 18 },
  { name: '10:00-11:00', value: 8 },
  { name: '11:00-12:00', value: 28 },
  { name: '12:00-13:00', value: 47 },
  { name: '13:00-14:00', value: 25 },
]

// Keep the same variable name for backward compatibility
export const msmePeakHours = msmePaymentPeakHours

// Weekly Cash Flow Trends - PAYMENT-CENTRIC VERSION
export const msmeWeeklyCashFlowTrends: ChartData[] = [
  { name: 'Week 1', value: 2150 },
  { name: 'Week 2', value: 2080 },
  { name: 'Week 3', value: 2320 },
  { name: 'Week 4', value: 2200 },
]

// Keep the same variable name for backward compatibility
export const msmeWeeklySalesTrends = msmeWeeklyCashFlowTrends

// Monthly Cash Flow Comparison - PAYMENT-CENTRIC VERSION
export const msmeMonthlyComparison: ChartData[] = [
  { name: 'Nov 2023', value: 7800 },
  { name: 'Dec 2023', value: 8200 },
  { name: 'Jan 2024', value: 8750 },
]

// Cash Flow Analysis - PAYMENT-CENTRIC VERSION
export const msmeCashFlowAnalysis: ProfitMarginData[] = [
  {
    name: 'Week 1',
    revenue: 5950.00,
    costs: 2400.00,
    grossProfit: 3550.00,
    margin: 59.7,
    date: '2024-01-07',
  },
  {
    name: 'Week 2',
    revenue: 6280.00,
    costs: 2500.00,
    grossProfit: 3780.00,
    margin: 60.2,
    date: '2024-01-14',
  },
  {
    name: 'Week 3',
    revenue: 7120.00,
    costs: 2750.00,
    grossProfit: 4370.00,
    margin: 61.4,
    date: '2024-01-21',
  },
  {
    name: 'Week 4',
    revenue: 6850.00,
    costs: 2650.00,
    grossProfit: 4200.00,
    margin: 61.3,
    date: '2024-01-28',
  },
]

// Keep the same variable name for backward compatibility
export const msmeProfitMarginData = msmeCashFlowAnalysis

// Transaction Time Patterns - PAYMENT-CENTRIC VERSION
export const msmeTransactionTimePatterns: RevenueBreakdown[] = [
  {
    name: 'Morning Rush (7-10 AM)',
    amount: 8250.00,
    percentage: 44.0,
    change: 12.3,
    color: '#3b82f6',
    description: 'Early morning payment activity',
  },
  {
    name: 'Lunch Peak (11 AM-2 PM)',
    amount: 5625.00,
    percentage: 30.0,
    change: 5.7,
    color: '#22c55e',
    description: 'Peak lunch time transactions',
  },
  {
    name: 'Afternoon Moderate (2-5 PM)',
    amount: 2812.50,
    percentage: 15.0,
    change: -8.2,
    color: '#f59e0b',
    description: 'Moderate afternoon activity',
  },
  {
    name: 'Evening Wind-down (5-8 PM)',
    amount: 1312.50,
    percentage: 7.0,
    change: 18.5,
    color: '#ef4444',
    description: 'Evening transaction activity',
  },
  {
    name: 'Off-Peak Hours',
    amount: 750.00,
    percentage: 4.0,
    change: 25.8,
    color: '#8b5cf6',
    description: 'Outside normal business hours',
  },
]

// Keep the same variable name for backward compatibility
export const msmeCustomerDemographics = msmeTransactionTimePatterns 