import { 
  KPICard, 
  ChartData, 
  FinancialKPI,
  CashFlowData,
  BusinessMetrics,
  FinancialHealthIndicator,
  RevenueBreakdown,
  ExpenseCategory,
  ProfitMarginData,
  BankAccount,
  Transaction,
  QRPayment,
  OpenFinanceConnection,
  ConsolidatedFinancialData,
  TransactionCategory,
  SupplierCustomerData,
} from './types'
import { 
  Users, 
  TrendingUp, 
  Shield, 
  Zap, 
  Target, 
  Award, 
  Heart, 
  Globe,
  DollarSign,
  ShoppingCart,
  UserCheck,
  BarChart3,
  Building2,
  CreditCard,
  QrCode,
  ArrowUpDown,
  PieChart,
  FileText,
  Calculator,
  Receipt,
  Truck,
  Store,
  Coffee,
  Car,
  Home,
  Smartphone,
  Utensils,
  Briefcase,
  Fuel,
  Stethoscope,
  GraduationCap,
  Gamepad2,
  Plane,
  Gift,
  Shirt,
  Wrench,
  Zap as ElectricIcon,
  Wifi,
  Music,
  Film,
  Book,
  Dumbbell,
  Scissors,
  Paintbrush,
  Flower,
  ShieldCheck,
  AlertCircle,
  CheckCircle2,
  Clock,
  MapPin,
  Phone,
  Mail,
  Globe2,
  Languages,
  Calendar,
  FileCheck,
  TrendingDown,
  AlertTriangle,
  CheckCircle,
  XCircle,
  Minus,
  Plus,
  Eye,
  EyeOff,
  Loader,
  RefreshCw,
  Download,
  Upload,
  Filter,
  Search,
  Settings,
  Bell,
  HelpCircle,
  LogOut,
  User,
  Edit,
  Trash,
  Copy,
  Share,
  ExternalLink,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  MoreHorizontal,
  MoreVertical
} from 'lucide-react'

// Malaysian MSME Business Profile
export const msmeBusinessProfile = {
  name: "Warung Nasi Lemak Kak Siti",
  owner: "Siti Aminah binti Abdullah",
  businessType: "Food & Beverage",
  category: "Traditional Malaysian Cuisine",
  established: "2019",
  location: "Taman Melawati, Kuala Lumpur",
  employees: 3,
  operatingHours: "7:00 AM - 2:00 PM",
  businessRegistration: "SA0123456789",
  gstNumber: "000123456789",
  description: "Traditional Malaysian nasi lemak stall serving authentic homemade recipes passed down through generations",
  specialties: ["Nasi Lemak", "Ayam Rendang", "Sambal Ikan Bilis", "Telur Dadar", "Acar Timun"],
  dailyCapacity: 150,
  averageOrderValue: 8.50,
  paymentMethods: ["Cash", "DuitNow QR", "Touch 'n Go eWallet", "GrabPay", "Maybank QRPay"]
}

// Malaysian MSME KPI Data
export const msmeKPIData: KPICard[] = [
  {
    id: '1',
    title: 'Monthly Revenue',
    value: 'RM 18,750',
    change: 15.2,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Total sales from nasi lemak and sides',
  },
  {
    id: '2',
    title: 'Daily Customers',
    value: '125',
    change: 8.7,
    changeType: 'increase',
    icon: Users,
    description: 'Average customers per day',
  },
  {
    id: '3',
    title: 'Profit Margin',
    value: '68%',
    change: 2.3,
    changeType: 'increase',
    icon: TrendingUp,
    description: 'Gross profit margin',
  },
  {
    id: '4',
    title: 'Connected Banks',
    value: '3',
    change: 0,
    changeType: 'stable',
    icon: Building2,
    description: 'Active bank accounts',
  },
]

// Malaysian Banking Data
export const msmeFinancialKPIs: FinancialKPI[] = [
  {
    id: 'daily_sales',
    title: 'Daily Sales',
    value: 'RM 1,125',
    change: 18.5,
    changeType: 'increase',
    icon: DollarSign,
    description: 'Average daily sales revenue',
    period: 'daily',
    currency: 'MYR',
    trend: 'up',
    target: 1200,
  },
  {
    id: 'monthly_profit',
    title: 'Monthly Profit',
    value: 'RM 12,750',
    change: 22.3,
    changeType: 'increase',
    icon: TrendingUp,
    description: 'Net profit after expenses',
    period: 'monthly',
    currency: 'MYR',
    trend: 'up',
    target: 15000,
  },
  {
    id: 'cash_flow',
    title: 'Cash Flow',
    value: 'RM 8,420',
    change: 12.8,
    changeType: 'increase',
    icon: BarChart3,
    description: 'Monthly net cash flow',
    period: 'monthly',
    currency: 'MYR',
    trend: 'up',
    target: 10000,
  },
  {
    id: 'ingredient_cost',
    title: 'Ingredient Cost',
    value: 'RM 6,000',
    change: -5.2,
    changeType: 'decrease',
    icon: ShoppingCart,
    description: 'Monthly ingredient expenses',
    period: 'monthly',
    currency: 'MYR',
    trend: 'down',
    target: 5500,
  },
  {
    id: 'digital_payments',
    title: 'Digital Payments',
    value: '76%',
    change: 31.2,
    changeType: 'increase',
    icon: QrCode,
    description: 'Non-cash payment percentage',
    period: 'monthly',
    trend: 'up',
    target: 80,
  },
  {
    id: 'customer_satisfaction',
    title: 'Customer Rating',
    value: '4.8/5',
    change: 2.1,
    changeType: 'increase',
    icon: Award,
    description: 'Average customer rating',
    period: 'monthly',
    trend: 'up',
    target: 4.9,
  },
]

// Malaysian Bank Accounts
export const msmeBankAccounts: BankAccount[] = [
  {
    id: 'acc_maybank_001',
    bankName: 'Maybank',
    bankCode: 'MBB',
    accountNumber: '1234567890',
    accountType: 'business',
    balance: 28750.50,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:30:00Z',
    iban: 'MY7701234567890123456789',
    swiftCode: 'MBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_publicbank_001',
    bankName: 'Public Bank',
    bankCode: 'PBB',
    accountNumber: '9876543210',
    accountType: 'savings',
    balance: 15800.75,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:25:00Z',
    iban: 'MY7702987654321098765432',
    swiftCode: 'PBBEMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
  {
    id: 'acc_cimb_001',
    bankName: 'CIMB Bank',
    bankCode: 'CIMB',
    accountNumber: '1122334455',
    accountType: 'checking',
    balance: 12200.25,
    currency: 'MYR',
    status: 'active',
    lastSyncTime: '2024-01-20T10:20:00Z',
    iban: 'MY7703112233445566778899',
    swiftCode: 'CIBBMYKL',
    isConnected: true,
    permissions: ['read_account', 'read_transactions', 'read_balance'],
  },
]

// Malaysian MSME Transactions
export const msmeTransactions: Transaction[] = [
  {
    id: 'txn_001',
    accountId: 'acc_maybank_001',
    amount: 850.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Nasi Lemak Sales',
    description: 'Daily sales - Nasi Lemak orders',
    counterpartyName: 'Cash & Digital Payments',
    date: '2024-01-20',
    timestamp: '2024-01-20T14:30:00Z',
    reference: 'DAILY-SALES-20240120',
    status: 'completed',
    balance: 28750.50,
    isRecurring: true,
    recurringPattern: 'daily',
    tags: ['food_sales', 'nasi_lemak', 'daily_revenue'],
    notes: 'Mixed payment methods: 60% digital, 40% cash',
  },
  {
    id: 'txn_002',
    accountId: 'acc_maybank_001',
    amount: -320.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Ingredients',
    subcategory: 'Fresh Ingredients',
    description: 'Pasar Borong Selayang - Rice, chicken, vegetables',
    counterpartyName: 'Pasar Borong Selayang',
    date: '2024-01-20',
    timestamp: '2024-01-20T06:15:00Z',
    reference: 'INGREDIENTS-20240120',
    status: 'completed',
    balance: 27900.50,
    isRecurring: true,
    recurringPattern: 'daily',
    tags: ['ingredients', 'market', 'cogs'],
    notes: 'Daily fresh ingredients purchase',
  },
  {
    id: 'txn_003',
    accountId: 'acc_publicbank_001',
    amount: 1200.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Catering Service',
    description: 'Office catering - Nasi Lemak for 50 pax',
    counterpartyName: 'ABC Consulting Sdn Bhd',
    date: '2024-01-19',
    timestamp: '2024-01-19T11:45:00Z',
    reference: 'CATERING-ABC-20240119',
    status: 'completed',
    balance: 15800.75,
    isRecurring: false,
    tags: ['catering', 'bulk_order', 'b2b'],
    notes: 'Special order for office lunch',
  },
  {
    id: 'txn_004',
    accountId: 'acc_maybank_001',
    amount: -180.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Utilities',
    subcategory: 'Electricity',
    description: 'TNB - Monthly electricity bill',
    counterpartyName: 'Tenaga Nasional Berhad',
    date: '2024-01-18',
    timestamp: '2024-01-18T09:20:00Z',
    reference: 'TNB-202401-001',
    status: 'completed',
    balance: 27720.50,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['utilities', 'fixed_cost', 'electricity'],
    notes: 'Stall electricity bill',
  },
  {
    id: 'txn_005',
    accountId: 'acc_cimb_001',
    amount: -450.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Staff',
    subcategory: 'Part-time Helper',
    description: 'Weekly salary - Aminah (kitchen helper)',
    counterpartyName: 'Aminah binti Yusof',
    date: '2024-01-17',
    timestamp: '2024-01-17T16:00:00Z',
    reference: 'SALARY-AMINAH-W3-2024',
    status: 'completed',
    balance: 12200.25,
    isRecurring: true,
    recurringPattern: 'weekly',
    tags: ['salary', 'part_time', 'staff'],
    notes: 'Kitchen helper - 30 hours/week',
  },
  {
    id: 'txn_006',
    accountId: 'acc_maybank_001',
    amount: -85.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Packaging',
    subcategory: 'Eco-friendly Containers',
    description: 'Biodegradable food containers and banana leaves',
    counterpartyName: 'Green Pack Malaysia',
    date: '2024-01-16',
    timestamp: '2024-01-16T13:30:00Z',
    reference: 'PACK-GREEN-20240116',
    status: 'completed',
    balance: 27635.50,
    isRecurring: true,
    recurringPattern: 'weekly',
    tags: ['packaging', 'eco_friendly', 'supplies'],
    notes: 'Sustainable packaging materials',
  },
  {
    id: 'txn_007',
    accountId: 'acc_publicbank_001',
    amount: 950.00,
    currency: 'MYR',
    type: 'credit',
    category: 'Sales',
    subcategory: 'Weekend Sales',
    description: 'Weekend high traffic - Nasi Lemak sales',
    counterpartyName: 'Weekend Customer Sales',
    date: '2024-01-15',
    timestamp: '2024-01-15T15:30:00Z',
    reference: 'WEEKEND-SALES-20240115',
    status: 'completed',
    balance: 14850.75,
    isRecurring: false,
    tags: ['weekend', 'high_traffic', 'sales'],
    notes: 'Weekend peak sales period',
  },
  {
    id: 'txn_008',
    accountId: 'acc_maybank_001',
    amount: -250.00,
    currency: 'MYR',
    type: 'debit',
    category: 'Marketing',
    subcategory: 'Social Media',
    description: 'Facebook & Instagram ads promotion',
    counterpartyName: 'Meta Malaysia',
    date: '2024-01-14',
    timestamp: '2024-01-14T10:15:00Z',
    reference: 'META-ADS-20240114',
    status: 'completed',
    balance: 27385.50,
    isRecurring: true,
    recurringPattern: 'monthly',
    tags: ['marketing', 'social_media', 'ads'],
    notes: 'Monthly social media advertising',
  },
]

// Cash Flow Data for Malaysian MSME
export const msmeCashFlowData: CashFlowData[] = [
  {
    name: 'Week 1',
    date: '2024-01-07',
    income: 5950.00,
    expenses: 2280.00,
    netCashFlow: 3670.00,
    cumulativeCashFlow: 3670.00,
  },
  {
    name: 'Week 2',
    date: '2024-01-14',
    income: 6280.00,
    expenses: 2450.00,
    netCashFlow: 3830.00,
    cumulativeCashFlow: 7500.00,
  },
  {
    name: 'Week 3',
    date: '2024-01-21',
    income: 7120.00,
    expenses: 2680.00,
    netCashFlow: 4440.00,
    cumulativeCashFlow: 11940.00,
  },
  {
    name: 'Week 4',
    date: '2024-01-28',
    income: 6850.00,
    expenses: 2590.00,
    netCashFlow: 4260.00,
    cumulativeCashFlow: 16200.00,
  },
]

// Revenue Breakdown by Menu Items
export const msmeRevenueBreakdown: RevenueBreakdown[] = [
  {
    name: 'Nasi Lemak Classic',
    amount: 11250.00,
    percentage: 60.0,
    change: 8.5,
    color: '#22c55e',
    description: 'Traditional nasi lemak with egg and anchovies',
  },
  {
    name: 'Nasi Lemak Ayam',
    amount: 4875.00,
    percentage: 26.0,
    change: 12.3,
    color: '#3b82f6',
    description: 'Nasi lemak with rendang chicken',
  },
  {
    name: 'Nasi Lemak Sambal Sotong',
    amount: 1500.00,
    percentage: 8.0,
    change: -2.1,
    color: '#f59e0b',
    description: 'Nasi lemak with spicy squid',
  },
  {
    name: 'Beverages',
    amount: 750.00,
    percentage: 4.0,
    change: 15.7,
    color: '#ef4444',
    description: 'Teh tarik, kopi, and fresh juices',
  },
  {
    name: 'Add-ons',
    amount: 375.00,
    percentage: 2.0,
    change: 6.2,
    color: '#8b5cf6',
    description: 'Extra egg, chicken, vegetables',
  },
]

// Expense Categories for Malaysian MSME
export const msmeExpenseCategories: ExpenseCategory[] = [
  {
    name: 'Ingredients & Raw Materials',
    amount: 6000.00,
    percentage: 60.0,
    budget: 6500.00,
    color: '#ef4444',
  },
  {
    name: 'Staff Wages',
    amount: 1800.00,
    percentage: 18.0,
    budget: 2000.00,
    color: '#3b82f6',
  },
  {
    name: 'Utilities (Electricity, Water)',
    amount: 720.00,
    percentage: 7.2,
    budget: 800.00,
    color: '#f59e0b',
  },
  {
    name: 'Packaging & Supplies',
    amount: 600.00,
    percentage: 6.0,
    budget: 700.00,
    color: '#10b981',
  },
  {
    name: 'Stall Rent',
    amount: 500.00,
    percentage: 5.0,
    budget: 500.00,
    color: '#8b5cf6',
  },
  {
    name: 'Marketing & Promotion',
    amount: 250.00,
    percentage: 2.5,
    budget: 300.00,
    color: '#06b6d4',
  },
  {
    name: 'Transportation',
    amount: 130.00,
    percentage: 1.3,
    budget: 200.00,
    color: '#84cc16',
  },
]

// Monthly Revenue Growth
export const msmeMonthlyRevenueGrowth: ChartData[] = [
  { name: 'Jul', value: 14200.00 },
  { name: 'Aug', value: 15800.00 },
  { name: 'Sep', value: 16500.00 },
  { name: 'Oct', value: 17200.00 },
  { name: 'Nov', value: 17800.00 },
  { name: 'Dec', value: 18750.00 },
]

// Daily Sales Pattern
export const msmeDailySalesPattern: ChartData[] = [
  { name: 'Mon', value: 780.00 },
  { name: 'Tue', value: 850.00 },
  { name: 'Wed', value: 920.00 },
  { name: 'Thu', value: 1050.00 },
  { name: 'Fri', value: 1180.00 },
  { name: 'Sat', value: 1420.00 },
  { name: 'Sun', value: 1300.00 },
]

// QR Payment Methods
export const msmeQRPayments: QRPayment[] = [
  {
    id: 'qr_duitnow_001',
    type: 'duitnow',
    amount: 0,
    currency: 'MYR',
    description: 'Warung Nasi Lemak Kak Siti - General Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 847,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'MY7701234567890',
  },
  {
    id: 'qr_touchngo_001',
    type: 'touchngo',
    amount: 0,
    currency: 'MYR',
    description: 'Touch n Go eWallet - Nasi Lemak Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 523,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'TNG-MSME-001',
  },
  {
    id: 'qr_grabpay_001',
    type: 'grabpay',
    amount: 0,
    currency: 'MYR',
    description: 'GrabPay - Food Payment',
    qrCode: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAYAAAA+s9J6...',
    isReusable: true,
    status: 'active',
    createdAt: '2024-01-01T00:00:00Z',
    usageCount: 324,
    businessName: 'Warung Nasi Lemak Kak Siti',
    merchantId: 'GRAB-MSME-001',
  },
]

// Open Finance Connections
export const msmeOpenFinanceConnections: OpenFinanceConnection[] = [
  {
    id: 'conn_maybank_001',
    providerId: 'maybank',
    providerName: 'Maybank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [msmeBankAccounts[0]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:30:00Z',
    lastSyncTime: '2024-01-20T10:30:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'maybank-msme-001',
    },
  },
  {
    id: 'conn_publicbank_001',
    providerId: 'publicbank',
    providerName: 'Public Bank',
    connectionType: 'bank',
    status: 'connected',
    accounts: [msmeBankAccounts[1]],
    permissions: ['read_account', 'read_transactions', 'read_balance'],
    consentExpiryDate: '2024-12-20T10:25:00Z',
    lastSyncTime: '2024-01-20T10:25:00Z',
    metadata: {
      apiVersion: '2.0',
      connectionId: 'publicbank-msme-001',
    },
  },
  {
    id: 'conn_duitnow_001',
    providerId: 'duitnow',
    providerName: 'DuitNow',
    connectionType: 'payment_service',
    status: 'connected',
    accounts: [],
    permissions: ['read_payments', 'create_qr', 'read_qr_status'],
    consentExpiryDate: '2024-12-20T10:00:00Z',
    lastSyncTime: '2024-01-20T10:00:00Z',
    metadata: {
      apiVersion: '3.0',
      merchantId: 'DUITNOW-MSME-001',
    },
  },
]

// Consolidated Financial Data
export const msmeConsolidatedFinancialData: ConsolidatedFinancialData = {
  totalBalance: 56751.50,
  totalIncome: 18750.00,
  totalExpenses: 10000.00,
  netCashFlow: 8750.00,
  accountsCount: 3,
  transactionsCount: 156,
  lastUpdated: '2024-01-20T10:30:00Z',
  currency: 'MYR',
  performanceMetrics: {
    monthlyGrowth: 15.2,
    expenseRatio: 0.53,
    savingsRate: 0.47,
    liquidityRatio: 5.7,
  },
}

// Transaction Categories
export const msmeTransactionCategories: TransactionCategory[] = [
  {
    id: 'cat_sales',
    name: 'Food Sales',
    type: 'income',
    color: '#22c55e',
    icon: 'Utensils',
    totalAmount: 16500.00,
    transactionCount: 98,
    percentage: 88.0,
    budget: 18000.00,
    trend: 'up',
    trendPercentage: 15.2,
  },
  {
    id: 'cat_catering',
    name: 'Catering Services',
    type: 'income',
    color: '#3b82f6',
    icon: 'Users',
    totalAmount: 2250.00,
    transactionCount: 8,
    percentage: 12.0,
    budget: 2500.00,
    trend: 'up',
    trendPercentage: 25.6,
  },
  {
    id: 'cat_ingredients',
    name: 'Ingredients',
    type: 'expense',
    color: '#ef4444',
    icon: 'ShoppingCart',
    totalAmount: -6000.00,
    transactionCount: 28,
    percentage: 60.0,
    budget: 6500.00,
    trend: 'down',
    trendPercentage: -5.2,
  },
  {
    id: 'cat_staff',
    name: 'Staff Wages',
    type: 'expense',
    color: '#f59e0b',
    icon: 'Users',
    totalAmount: -1800.00,
    transactionCount: 12,
    percentage: 18.0,
    budget: 2000.00,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_utilities',
    name: 'Utilities',
    type: 'expense',
    color: '#8b5cf6',
    icon: 'Zap',
    totalAmount: -720.00,
    transactionCount: 6,
    percentage: 7.2,
    budget: 800.00,
    trend: 'down',
    trendPercentage: -8.3,
  },
  {
    id: 'cat_supplies',
    name: 'Supplies & Packaging',
    type: 'expense',
    color: '#06b6d4',
    icon: 'Package',
    totalAmount: -600.00,
    transactionCount: 8,
    percentage: 6.0,
    budget: 700.00,
    trend: 'stable',
    trendPercentage: 0.0,
  },
  {
    id: 'cat_marketing',
    name: 'Marketing',
    type: 'expense',
    color: '#84cc16',
    icon: 'Megaphone',
    totalAmount: -250.00,
    transactionCount: 4,
    percentage: 2.5,
    budget: 300.00,
    trend: 'up',
    trendPercentage: 12.5,
  },
]

// Financial Health Indicators
export const msmeFinancialHealthIndicators: FinancialHealthIndicator[] = [
  {
    id: 'liquidity_ratio',
    name: 'Liquidity Ratio',
    value: 5.7,
    status: 'healthy',
    recommendation: 'Strong cash position for daily operations',
    trend: 'stable',
  },
  {
    id: 'profit_margin',
    name: 'Profit Margin',
    value: 68.0,
    status: 'healthy',
    recommendation: 'Excellent profit margins for food business',
    trend: 'improving',
  },
  {
    id: 'ingredient_cost_ratio',
    name: 'Ingredient Cost Ratio',
    value: 32.0,
    status: 'healthy',
    recommendation: 'Well-controlled ingredient costs',
    trend: 'stable',
  },
  {
    id: 'digital_payment_adoption',
    name: 'Digital Payment Adoption',
    value: 76.0,
    status: 'healthy',
    recommendation: 'Good digital payment integration',
    trend: 'improving',
  },
  {
    id: 'daily_sales_consistency',
    name: 'Sales Consistency',
    value: 89.0,
    status: 'healthy',
    recommendation: 'Stable daily sales performance',
    trend: 'stable',
  },
]

// Business Growth Metrics
export const msmeBusinessGrowthMetrics: BusinessMetrics[] = [
  {
    id: 'customer_retention',
    name: 'Customer Retention',
    completionRate: 85.2,
    averageTime: 0,
    dropOffRate: 14.8,
    satisfactionScore: 4.8,
    date: '2024-01-20',
  },
  {
    id: 'order_frequency',
    name: 'Order Frequency',
    completionRate: 92.1,
    averageTime: 0,
    dropOffRate: 7.9,
    satisfactionScore: 4.6,
    date: '2024-01-20',
  },
  {
    id: 'digital_adoption',
    name: 'Digital Payment Adoption',
    completionRate: 76.0,
    averageTime: 0,
    dropOffRate: 24.0,
    satisfactionScore: 4.2,
    date: '2024-01-20',
  },
  {
    id: 'operational_efficiency',
    name: 'Operational Efficiency',
    completionRate: 88.5,
    averageTime: 0,
    dropOffRate: 11.5,
    satisfactionScore: 4.4,
    date: '2024-01-20',
  },
]

// Popular Menu Items Performance
export const msmeMenuPerformance: ChartData[] = [
  { name: 'Nasi Lemak Classic', value: 450 },
  { name: 'Nasi Lemak Ayam', value: 195 },
  { name: 'Nasi Lemak Sotong', value: 60 },
  { name: 'Teh Tarik', value: 180 },
  { name: 'Kopi O', value: 120 },
  { name: 'Extra Egg', value: 85 },
]

// Peak Hours Analysis
export const msmePeakHours: ChartData[] = [
  { name: '7:00-8:00', value: 45 },
  { name: '8:00-9:00', value: 85 },
  { name: '9:00-10:00', value: 65 },
  { name: '10:00-11:00', value: 35 },
  { name: '11:00-12:00', value: 95 },
  { name: '12:00-13:00', value: 125 },
  { name: '13:00-14:00', value: 85 },
]

// Weekly Sales Trends
export const msmeWeeklySalesTrends: ChartData[] = [
  { name: 'Week 1', value: 5950 },
  { name: 'Week 2', value: 6280 },
  { name: 'Week 3', value: 7120 },
  { name: 'Week 4', value: 6850 },
]

// Monthly comparison
export const msmeMonthlyComparison: ChartData[] = [
  { name: 'Nov 2023', value: 16800 },
  { name: 'Dec 2023', value: 17200 },
  { name: 'Jan 2024', value: 18750 },
]

// Profit Margin Data
export const msmeProfitMarginData: ProfitMarginData[] = [
  {
    name: 'Week 1',
    revenue: 5950.00,
    costs: 1890.00,
    grossProfit: 4060.00,
    margin: 68.2,
    date: '2024-01-07',
  },
  {
    name: 'Week 2',
    revenue: 6280.00,
    costs: 1960.00,
    grossProfit: 4320.00,
    margin: 68.8,
    date: '2024-01-14',
  },
  {
    name: 'Week 3',
    revenue: 7120.00,
    costs: 2150.00,
    grossProfit: 4970.00,
    margin: 69.8,
    date: '2024-01-21',
  },
  {
    name: 'Week 4',
    revenue: 6850.00,
    costs: 2100.00,
    grossProfit: 4750.00,
    margin: 69.3,
    date: '2024-01-28',
  },
]

// Customer Demographics
export const msmeCustomerDemographics: RevenueBreakdown[] = [
  {
    name: 'Office Workers',
    amount: 8250.00,
    percentage: 44.0,
    change: 12.3,
    color: '#3b82f6',
    description: 'Nearby office employees',
  },
  {
    name: 'Residents',
    amount: 5625.00,
    percentage: 30.0,
    change: 5.7,
    color: '#22c55e',
    description: 'Local neighborhood residents',
  },
  {
    name: 'Students',
    amount: 2812.50,
    percentage: 15.0,
    change: -8.2,
    color: '#f59e0b',
    description: 'University and college students',
  },
  {
    name: 'Tourists',
    amount: 1312.50,
    percentage: 7.0,
    change: 18.5,
    color: '#ef4444',
    description: 'Food tourists and visitors',
  },
  {
    name: 'Food Delivery',
    amount: 750.00,
    percentage: 4.0,
    change: 25.8,
    color: '#8b5cf6',
    description: 'GrabFood and Foodpanda orders',
  },
] 